
export const LEAD_SOURCES = [
  'SOI',
  'FSBO',
  'Expired',
  'Open House',
  'Farming',
  'Sign Calls',
  'Ad Calls',
  'Internal Referral',
  'Referral',
  'Referral to Other Agent',
  'Direct Mail',
  'Social Media',
  'Agent Referral',
  'Zillow',
  'Zillow Flex',
  'Zillow NLL',
  'Zillow Preferred',
  'UpNest',
  'Homelight',
  'OpCity',
  'OpCity MVIP',
  'Realtor.com',
  'FollowUpBoss',
  'Agent Website',
  'Relocation Company',
  'Other'
] as const;
